### PR TITLE
feat: la liga teams endpoint

### PR DESCRIPTION
**Pull request by GuilhermeFernandes01**
Hi @ageddesi! Relates to #159.

- Add la liga endpoint
- Create helper to get random subarray, which will be useful to many other routes
- Add tests to la liga endpoint
- Add jest coverage report (which I think is very useful)
- Add supertest types

PS: coverage report is not working for routes files by the way it is implemented.

### CODE REVIEW

**Comment by ageddesi** [comment]
@GuilhermeFernandes01 Seems to be a package.json conflict :P

**Review by ageddesi — DISMISSED** [review]

**Comment by ageddesi** [comment]
HI @GuilhermeFernandes01 can you delete package-lock.json and node modules then re-run npm instal.

This should resolve the conflicts and then ready to pull add tag with that sexy hacktober-accepted :P

**Comment by GuilhermeFernandes01** [comment]
Hey @ageddesi sorry for the delay, merge problems fixed.

**Review by ageddesi — APPROVED** [review]

**Comment by ageddesi** [comment]
Thanks. Appreciate the work on this

**Pull request merged**
