### PR TITLE
added timezones api

### PR DESCRIPTION
**Pull request by fadkeabhi**
get all timezones and random timezones

### CODE REVIEW

**Comment by fadkeabhi** [comment]
please accept with hacktoberfest label

**Comment by ageddesi** [comment]
hi @fadkeabhi , Thank you for the PR, this is awesome work. Are you able to update the swagger file with your new endpoints as well.

**Comment by fadkeabhi** [comment]
no, I have just done the coding part.

**Comment by fadkeabhi** [comment]
updated swagger in this commit, please look into it.

**Comment by ageddesi** [comment]
@all-contributors please add @fadkeabhi for code

**Comment by ageddesi** [comment]
Thank you @fadkeabhi for the work on this ticket :) Happy Hacktoberfest

**Pull request merged**
