### PR TITLE
Feat: Digital currency transaction list endpoint

### PR DESCRIPTION
**Pull request by filipkujawa**
**Endpoint Summary:**
Returns the list of transactions performed by an address
Inspired by the Etherscan accounts endpoint 

Related to #14 

**Endpoint Path:**
`/currencies/digital-coins/ethereum/tx-list/:address?`

**Part of an Example Response: **
```
{
"blockNumber": "14923692",
"timeStamp": "1654646570",
"hash": "0xaa45b4858ba44230a5fce5a29570a5dec2bf1f0ba95bacdec4fe8f2c4fa99338",
"nonce": "7",
"blockHash": "0x8df71a12a8c06b36c06c26bf6248857dd2a2b75b6edbb4e33e9477078897b282",
"transactionIndex": "27",
"from": "0x9aa99c23f67c81701c772b106b4f83f6e858dd2e",
"to": "0xc5102fe9359fd9a28f877a67e36b0f050d81a3cc",
"value": "0",
"gas": "6000000",
"gasPrice": "125521409858",
"isError": "0",
"txreceipt_status": "1",
"input": "0xa9059cbb000000000000000000000000313143c4088a47c469d06fe3fa5fd4196be6a4d600000000000000000000000000000000000000000003b8e97d229a2d54800000",
"contractAddress": "",
"cumulativeGasUsed": "1977481",
"gasUsed": "57168",
"confirmations": "746430",
"methodId": "0xa9059cbb",
"functionName": "transfer(address _to, uint256 _value)"
}, 
```

### CODE REVIEW

**Comment by filipkujawa** [comment]
#14

**Comment by ageddesi** [comment]
hi @filipkujawa Any updates on this?

**Comment by filipkujawa** [comment]
> hi @filipkujawa Any updates on this?

Update on what?

**Comment by ageddesi** [comment]
@filipkujawa I have left comments on the PR that need looking into before we can Merge this code in.

**Comment by filipkujawa** [comment]
I can't find any comments on the PR

**Review by ageddesi — CHANGES_REQUESTED** [review]

**Comment by ageddesi** [comment]
Sorry @filipkujawa it appears my comments where in draft mode so was not submitted. This has now been sorted.

**Review by ageddesi — DISMISSED** [review]

**Comment by ageddesi** [comment]
Hi @filipkujawa Sorry just a final merge conflict for you to resolve and this will go straight in. Great job.

**Comment by ageddesi** [comment]
Super work, thank you 👍 Happy Hacktoberfest

**Pull request merged**
