### PR TITLE
improving unit tests and openapi definitions.

### LINKED ISSUE #127: [Tests] - Timezones Module
The timezones module is missing tests

### PR DESCRIPTION
**Pull request by pjunior94**
improving unit tests and openapi definitions. fixes #127

### CODE REVIEW

**Comment by ageddesi** [comment]
HI @pjunior94 just some conflicts to resolve and then all looks good for me to Merge :) Thank you 👍

**Comment by pjunior94** [comment]
> 

Hi @ageddesi it seems like I don't have write permissions to write my changes to this repo.

**Comment by ageddesi** [comment]
That is strange as it is your repo :) not sure why you can merge our origin back into your repo.

**Comment by pjunior94** [comment]
> That is strange as it is your repo :) not sure why you can merge our origin back into your repo.

Okay, I was just able to merge it @ageddesi. I appreciate if you approve it 👍🏻

**Review by computamike — APPROVED** [review]
@ageddesi has already seen these changes so approving... Had a look and they seem fine to me.

**Pull request merged**
