### PR TITLE
Folder refactor

### PR DESCRIPTION
**Pull request by headStyleColorRed**
## Issue
Working on this issue #230

## Moved folders
- [x] Modules
- [x] Tests
- [x] Utils

## Tests
- [x] Passing

## Suggestions
If you think @ageddesi that more files should be added, please tell me :)

### CODE REVIEW

**Comment by ageddesi** [comment]
Hi @headStyleColorRed Sorry we have just released a new version. So now is a perfect time to merge back in the branch and resolve the conflict issues. Once that is done I will make sure this is the only one merged in next.

**Comment by headStyleColorRed** [comment]
> Hi @headStyleColorRed Sorry we have just released a new version. So now is a perfect time to merge back in the branch and resolve the conflict issues. Once that is done I will make sure this is the only one merged in next.

Perfect!! Yesterday i was struggling with all the conflicts xd I'll get on it :D

**Comment by headStyleColorRed** [comment]
Alright @ageddesi! The pr has been updated

**Review by ageddesi — APPROVED** [review]

**Comment by ageddesi** [comment]
Hi @headStyleColorRed Thanks for the massive refactor. :) 👍 Happy Hacktoberfest

**Pull request merged**
