### PR TITLE
Element API endpoints closes ageddesi/Mocked-API#107

### LINKED ISSUE #107: [OpenAPI] - Elements API Endpoints
The elements api endpoints need open api comments being added for documentation

### PR DESCRIPTION
**Pull request by VLN37**
Hey there, happy hacktoberfest!

Contribution guidelines asks for tests but endpoint and test issues are separate, i figured it was ok? Still starting with typescript. Tried some edge cases in insomnia though!

### CODE REVIEW

**Comment by ageddesi** [comment]
Hey @VLN37 
We have updated our codebase to now have tests and swagger is no longer needed to be updated, instead we do OpenAPI comments directly in the API source file. 

I have also pointed the merge target to our v0.13.0 which has the latest code on it. If you are able to resolve the conflict and if you have time update with the tests and OpenAPI Comments that would be ace 👍

**Comment by VLN37** [comment]
I'll see what i can do.

Tried to link to the issue but it didn't work, any ideas on that?

**Comment by ageddesi** [comment]
Ahhh I follow what you mean now. If you want to do the tests I can assign that ticket to you as well and I will close them both at the same time for this PR.

**Comment by VLN37** [comment]
0.13.0 already has commits for the issue i was pushing for... i guess it's whatever now...

Did learn some while at it, good luck fellow.

**Comment by ageddesi** [comment]
Ah sorry @VLN37 there is a lot going on the last 2 days, Thanks for the help. There is always some more smaller tasks if you have time.

**Pull request closed without merging**
