### PR TITLE
feat: add music-routes

### PR DESCRIPTION
**Pull request by rizkyian78**

### CODE REVIEW

**Comment by ageddesi** [comment]
Hi @rizkyian78 Thank you so much for the PR, are you able to update this to include taking in a qty for the amount of them to be returned. :)

**Comment by rizkyian78** [comment]
already done sir

**Comment by ageddesi** [comment]
Thanks so much for the work @rizkyian78 , Happy Hacktoberfest. Please star the repo if you like what we are doing.

**Comment by ageddesi** [comment]
@all-contributors please add @rizkyian78  for code

**Pull request merged**
