### PR TITLE
Add quote routes

### PR DESCRIPTION
**Pull request by Coskntkk**

### CODE REVIEW

**Comment by Coskntkk** [comment]
#hacktoberfest

**Comment by ageddesi** [comment]
Thank you for the PR @Coskntkk, just 2 small things.

Can you remove the app.post("/quotes", endpoint please. At this time we will only allow you to contribute via the github so we can monitor and maintain what is added. 

secondly can you a qty to the first endpoint with a default value so it can return n number of results.

**Comment by Coskntkk** [comment]
Thank you for telling me about this issues, i hope you all like my contribution. Happy hacking to you all!

**Comment by ageddesi** [comment]
@all-contributors please add @Coskntkk for code

**Comment by ageddesi** [comment]
Thank you so much @Coskntkk, really great work. Please star the repo :) and hope you join for another soon.

**Pull request merged**
