### PR TITLE
chore: Adding Environment support for Swagger localhost

### PR DESCRIPTION
**Pull request by computamike**
This PR fixes issue #114, allowing a developer to set up their local machine as part of the cloning process.

- A .env.example file has been created.  A developer could copy or rename this file to `.env`...
- To make it consistent for all users, a NPM script has been set up - running `npm run config` will set up the .env file.  
- A new utility script has been added - config.ts, which performs the copy.

### CODE REVIEW

**Comment by ageddesi** [comment]
Hi @computamike Thanks for this a bunch. 
Please can you check the conflicts now that I have updated the target of the merge to v0.13.0

**Comment by computamike** [comment]
Hi @ageddesi - I have re-factored the configuration - it seems that the system now uses a JS class rather than a JSON object for configuration - which I actually think is better.  I struggled a bit with trying to fix the code issues.

Have also seem some unused dependencies (in the swagger config) - but I guess that's a job for an other time.

**Comment by ageddesi** [comment]
@all-contributors add @computamike code

**Comment by ageddesi** [comment]
Thanks @computamike for the amazing work, i will raise a ticket to remove the unused dependencies.

**Pull request merged**
