### PR TITLE
Auto Generate Swagger Docs

### PR DESCRIPTION
**Pull request by tzii**

### CODE REVIEW

**Comment by tzii** [comment]
@ageddesi it's ready for review

**Comment by ageddesi** [comment]
Hi @tzii I will check this out later on today, thank you for the hard work on this.

**Comment by ageddesi** [comment]
Hi @tzii , This is fantastic work. I really appreciate it. Can you just fix the one merge conflict and I will happily merge this in :) 
This was a big bug bare to get it working so I am happy it is now done.

**Comment by tzii** [comment]
I think it is good now.

**Comment by ageddesi** [comment]
Thanks @tzii for the amazing work on this :) 👍 
@all-contributors please add @tzii for code, doc

**Pull request merged**
